core/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns
from django.conf.urls.defaults import url

urlpatterns = patterns("core.views",
    url(r"^$", "showMainPage"),
    url(r"^rejestracja/(\w{40})/$", "confirmRegistration"),
    url(r"^panel-uzytkownika/$", "showPanel"),
    url(r"^panel-uzytkownika/moje-dane/$", "changeUserData"),
    url(r"^panel-uzytkownika/dodaj-przepis/$", "addRecipe"),
    url(r"^panel-uzytkownika/ksiazka-kucharska/$", "showCookBook"),
    url(r"^zmien-haslo/$", "changeUserPassword"),
    url(r"^wylogowanie/$", "logoutPanel"),
    url(r"^przepisy-ajax/$", "returnRecipesForAjax"),
    url(r"^bing-token/$", "returnBingToken"),
    url(r"^szukaj/(?P<page>[\w\-_]+)/$", "showSearchResults", name = "search-results"),
    url(r"^(?P<subpage>[\w\-_]+)/$", "showSubpage", name = "subpage"),
    url(r"^(?P<slug>[\w\-_]+)\-(?P<pk>[\d]+)\.html$", "showRecipe"),
    url(r"^(?P<slug>[\w\-_]+)\-(?P<pk>[\d]+)\.html&action=(?P<action>[\w\-_]+)$", "runAction"),
    url(r"^captcha.png/(?P<url>[\w\-_]+)/$", "captchaGenerator", name = "captcha"),
)

ekk/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url

from django.conf import settings

from django.contrib import admin
admin.autodiscover()

handler500 = "core.views.error500"
handler404 = "core.views.error404"

urlpatterns = patterns("",
    url(r"static/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.STATIC_TEMPLATES}),
    url(r"^statics/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.STATIC_ROOT}, name = "statics"),
    url(r"^media/(?P<path>.*)$", "django.views.static.serve", {"document_root" : settings.MEDIA_ROOT}, name = "media"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^sitemap", include("sitemap.urls")),
    url(r"^robots\.txt$", include("robots.urls")),
    url(r"^grappelli/", include("grappelli.urls")),
    url(r"", include("core.urls")),
)

core/models.py
# -*- coding: utf-8 -*-

from django.db import models

from django.contrib.auth.models import User
from django.contrib.auth.models import Group

from django.core.mail import EmailMessage

import string
from random import choice

from cms.utils import PasswordGenerator
from cms.utils import _slugify

class Category(models.Model):
    name = models.CharField(u"Nazwa", max_length = 30)

    class Meta:
        verbose_name = u"kategorię"
        verbose_name_plural = u"kategorie"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Ingredient(models.Model):
    name = models.CharField(u"Nazwa", max_length = 30, unique = True)   

    class Meta:
        verbose_name = u"składnik"
        verbose_name_plural = u"składniki"

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class RegisteredUser(models.Model):
    user = models.OneToOneField(User, editable = False, null = True, blank = True)
    activation_key = models.CharField(max_length = 40, editable = False)
    password = models.CharField(u"Hasło", max_length = 54, editable = False)
    date = models.DateTimeField(u"Data rejestracji", auto_now_add = True) 
    fname = models.CharField(u"Imię", max_length = 20)
    lname = models.CharField(u"Nazwisko", max_length = 30)
    nick = models.CharField(u"Nick", max_length = 12, blank = True, null = True)
    email = models.EmailField(u"E-mail", unique = True)
    confirmation = models.BooleanField(u"Stan konta (aktywne)", default = False)

    class Meta:
        verbose_name = u"użytkownika"
        verbose_name_plural = u"użytkownicy"

    def save(self, *args, **kwargs):
        size = 40

        if not self.pk:
            super(RegisteredUser, self).save(*args, **kwargs)

        if not self.password:
            self.pin = unicode(self.pk).zfill(4)
            self.activation_key = "".join([choice(string.letters + string.digits) for x in xrange(size)])

            pw = PasswordGenerator(8)
            self.newPassword = pw.pswdGenerator()
            self.password = pw.pswdHash(password = self.newPassword)

            self.user = User.objects.create_user(self.email, self.email, self.newPassword)
            self.user.is_staff = False
            self.user.save()

            group = Group.objects.get(name = u"Użytkownicy")
            group.user_set.add(self.user)

            title = u"e-kk.pl - Twoje konto zostało utworzone"
            text = u"Witaj,<br><br>Z tej strony kłania się administrator z <a href=\"http://e-kk.pl\" title=\"Internetowa książka kucharska\">e-kk.pl</a>.<br><br>Widzię, że <strong>utworzyłeś</strong> konto w naszym serwisie. Chcemy Cię prosić o jego potwierdzenie.<br><br>W tym celu wystarczy kliknąć ten <a href=\"http://e-kk.pl/rejestracja/%s/\" title=\"Link aktywacyjny\">link aktywacyjny</a>. Wówczas uzyskasz dostęp do panelu użytkownika i szerszej oferty naszego serwisu.<br><br>Twój login i hasło to:<br><br><strong>Login:</strong> %s<br><strong>Hasło:</strong> %s<br><br>Jeśli nie rejestrowałeś u nas konta, to proszę zignoruj tę wiadomość.<br><br>Z poważaniem,<br>Administrator<br><a href=\"mailto:support@e-kk.pl\" title=\"support@e-kk.pl\">support@e-kk.pl</a>" % (self.activation_key, self.email, self.newPassword)
            who = u"e-kk.pl <support@e-kk.pl>"

            msg = EmailMessage(title, text, who, [self.email])
            msg.content_subtype = "html"
            msg.send()

        if self.pk:
            user = User.objects.get(pk = self.user_id)
    
            if user.email != self.email:
                user.username = self.email
                user.email = self.email
                user.save()

        super(RegisteredUser, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.user.delete()

        title = u"e-kk.pl - Twoje konto zostało usunięte"
        text = u"Witaj,<br><br>Z tej strony kłania się administrator z <a href=\"http://e-kk.pl\" title=\"Internetowa książka kucharska\">e-kk.pl</a>.<br><br>Twoje konto zostało właśnie <strong>usunięte</strong>.<br><br>Z poważaniem,<br>Administrator<br><a href=\"mailto:support@e-kk.pl\" title=\"support@e-kk.pl\">support@e-kk.pl</a>"
        who = u"e-kk.pl <support@e-kk.pl>"

        msg = EmailMessage(title, text, who, [self.email])
        msg.content_subtype = "html"
        msg.send()

        super(RegisteredUser, self).delete(*args, **kwargs)

    def __str__(self):
        return self.email

    def __unicode__(self):
        return self.email

class Recipe(models.Model):
    author = models.ForeignKey(RegisteredUser, verbose_name = u"Autor", limit_choices_to = {"confirmation" : True})
    parent = models.ForeignKey(Category, verbose_name = u"Kategoria")
    name = models.CharField(u"Tytuł", max_length = 50)
    description = models.TextField(u"Opis przyrządzania")
    products = models.ManyToManyField(Ingredient, verbose_name = u"Składniki")
    products.help_text = ""
    vegan = models.BooleanField(u"Danie wegetariańskie", default = False)
    jude = models.BooleanField(u"Danie koszerne", default = False)
    photo = models.ImageField(verbose_name = u"Zdjęcie", upload_to = "photos", blank = True, null = True)
    p_vote = models.PositiveIntegerField(editable = False, default = 0)
    m_vote = models.PositiveIntegerField(editable = False, default = 0)
    date = models.DateTimeField(u"Data rejestracji", auto_now_add = True)
    url = models.SlugField(verbose_name = u"Adres url", editable = False, max_length = 200)

    def points(self):
        return u"%d/%d" % (self.p_vote, self.m_vote)

    points.allow_tags = True
    points.short_description = u"Punktacja"

    class Meta:
        verbose_name = u"przepisu"
        verbose_name_plural = u"przepisy"

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Recipe, self).save(*args, **kwargs)

        self.url = u"%s-%s.html" % (_slugify(self.name), self.pk)

        self.description = self.description.replace("\r\n", "<br>")

        super(Recipe, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return u"/%s" % self.url

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Score(models.Model):
    user = models.ForeignKey(RegisteredUser, verbose_name = u"Autor")
    recipe = models.ForeignKey(Recipe, verbose_name = u"Przepis")

    class Meta:
        verbose_name = u"oddany głos"
        verbose_name_plural = u"oddane głosy"

    def __str__(self):
        return self.user.email

    def __unicode__(self):
        return self.user.email

class Book(models.Model):
    owner = models.ForeignKey(RegisteredUser, verbose_name = u"Autor", limit_choices_to = {"confirmation" : True})
    storage = models.ManyToManyField(Recipe, verbose_name = u"Przepisy")

    class Meta:
        verbose_name = u"książkę kucharską"
        verbose_name_plural = u"książka kucharska"

    def __str__(self):
        return self.owner.email

    def __unicode__(self):
        return self.owner.email

cms/forms.py
# -*- coding: utf-8 -*-

from django import forms

from core.models import Category

from django.conf import settings

import os

def handle_uploaded_and_clear_file(f, clear = False):
    path = "%s/recipes/" % (settings.MEDIA_ROOT)

    if not clear:
        if f.size > 2621440:
            return u"Przekroczono maksymalny rozmiar pliku (2.5 MB)."

        if os.path.splitext(f.name)[1] not in (".png", ".gif", ".jpg", ".jpeg"):
            return u"Niedozwolony typ pliku. Załącznik obsługuje wyłącznie: png, gif, jpg i jpeg."

        if not os.path.exists(path):
            os.mkdir(path)

        destination = open("%s%s" % (path, f.name), "wb+")

        for chunk in f.chunks():
            destination.write(chunk)

        destination.close()

        return "/media/recipes/%s" % f.name
    else:
        os.remove("%s/%s" % (path, f))

class RegisterForm(forms.Form):
    flname = forms.CharField(max_length = 50, widget = forms.TextInput(attrs = {"title" : u"Wpisz imię i nazwisko"}))
    email = forms.EmailField(widget = forms.TextInput(attrs = {"title" : u"Wpisz adres e-mail"}))
    nick = forms.CharField(max_length = 12, widget = forms.TextInput(attrs = {"title" : u"Wpisz nick"}), required = False)
    token = forms.CharField(max_length = 8, widget = forms.TextInput(attrs = {"title" : u"Przepisz token z obrazka", "id" : "captcha", "placeholder" : "Przepisz token z obrazka"}))
    regulations = forms.BooleanField(widget = forms.CheckboxInput(attrs = {"title" : u"Zaakceptuj regulamin", "id" : "chk"}), required = True, initial = False)

class LoginForm(forms.Form):
    login = forms.EmailField(widget = forms.TextInput(attrs = {"title" : u"Wpisz adres e-mail"}))
    password = forms.CharField(max_length = 8, widget = forms.PasswordInput(attrs = {"title" : u"Wpisz hasło"}))

class UserDataForm(forms.Form):
    fname = forms.CharField(max_length = 12, widget = forms.TextInput(attrs = {"title" : u"Wpisz imię",}))
    lname = forms.CharField(max_length = 20, widget = forms.TextInput(attrs = {"title" : u"Wpisz nazwisko"}))
    nick = forms.CharField(max_length = 12, widget = forms.TextInput(attrs = {"title" : u"Wpisz nick"}), required = False)

class AddRecipe(forms.Form):
    name = forms.CharField(max_length = 50, widget = forms.TextInput(attrs = {"title" : u"Wpisz tytuł"}))
    category = forms.ChoiceField(choices = [(category.id, category.name) for category in Category.objects.all()])
    text = forms.CharField(widget = forms.Textarea(attrs = {"title" : u"Wpisz opis"}))
    products = forms.CharField(widget = forms.Textarea(attrs = {"title" : u"Wpisz składniki"}))
    vegan = forms.BooleanField(widget = forms.CheckboxInput(attrs = {"title" : u"Danie wegetariańskie", "style" : "margin-top: 10px; display: inline-block;height: 13px; width: 20px;"}), required = False, initial = False)
    jude = forms.BooleanField(widget = forms.CheckboxInput(attrs = {"title" : u"Danie koszerne", "style" : "margin: 10px 0 0 30px; display: inline-block;height: 13px; width: 20px;"}), required = False, initial = False)
    photo = forms.FileField(required = False)

core/templates/base.html
{% spaceless %}
{% load url from future %}
<!DOCTYPE html>
<html lang="pl-PL">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <meta name="author" content="e-kk.pl">
        <meta name="robots" content="index, follow">
        <meta name="description" content="{{ config.description }}">
        <meta name="keywords" content="{{ config.keywords }}">
        {% block keywords %}{% endblock %}
    
        <title>{% block title %}{% endblock %} - e-kk.pl</title>
    
        <link rel="shortcut icon" href="{% url 'statics' 'images/favicon.ico' %}">
    
        <link href="{% url 'statics' 'css/style.css' %}" rel="stylesheet" type="text/css"> 
	<link href="{% url 'statics' 'js/autocomplete/jquery.autocomplete.css' %}" rel="stylesheet" type="text/css">

        {% block css %}{% endblock %}
    </head>
    <body>
    	<header>
    	    {% if not request.user.is_authenticated %}
                <a href="/logowanie/">Zaloguj się</a>
                <a href="/rejestracja/">Zarejestruj się</a>
    	    {% else %}
        	    <a href="/wylogowanie/">Wyloguj się</a>
        	    {% if not request.user.is_superuser %}
                    <a href="/panel-uzytkownika/">Panel użytkownika</a>
                {% else %}
                    <a href="/admin/">Panel administratora</a>
                {% endif %}
    	    {% endif %}
    	    <a href="/">Szukaj przepisów</a>
    	    <p>e-kk.pl - (nie)Typowa studencka lodówka</p>
    	</header>
        <section>
            <div class="custom">
                <div class="jbgallery"> 
    	            <ul> 
 	                <li><a href="{% url 'statics' 'images/bg2.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg3.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg4.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg5.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg6.jpg' %}"></a></li>
    	                <li><a href="{% url 'statics' 'images/bg7.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg8.jpg' %}"></a></li> 
    	                <li><a href="{% url 'statics' 'images/bg9.jpg' %}"></a></li>
    	            </ul> 
                </div>
            </div>
            {% block content %}{% endblock %}
        </section>
        <script type="text/javascript" src="{% url 'statics' 'js/jquery-1.9.1.min.js' %}"></script>
        <script type="text/javascript" src="{% url 'statics' 'js/jbgallery-2.0.js' %}"></script>
        <script type="text/javascript" src="{% url 'statics' 'js/bg-gallery.js' %}"></script>
        <script type="text/javascript">$j(document).ready(function(){$j(".jbgallery").jbgallery({menu:"numbers",style:"zoom",slideshow:true,clickable:false});});</script>
	<script type="text/javascript" src="{% url 'statics' 'js/autocomplete/lib/jquery.js' %}"></script>
	<script type="text/javascript" src="{% url 'statics' 'js/autocomplete/jquery.autocomplete.js' %}"></script>
	<script type="text/javascript">$(document).ready(function(){var cities=$.ajax({url:"/przepisy-ajax/",type:"GET",async:false}).responseText.split(',');$("#id_phrase").focus().autocomplete(cities);});</script>
	{% block bing %}{% endblock %}
    </body>
</html>
{% endspaceless %}

core/templates/panel.html
{% extends "index.html" %}
    {% load url from future %}

    <title>{% block title %}{% if userdataform %}Moje dane{% elif addRecipe %}Dodaj przepis{% elif cookbook %}Książka kucharska{% else %}Panel użytkownika{% endif %}{% endblock %} - e-kk.pl</title>

    {% block content %}
        <section style="float: left;background:none;border:none">
            <article id="panel">
                <section id="menu">
                    <h2>Panel użytkownika</h2>
                    <a href="/panel-uzytkownika/dodaj-przepis/" title="Dodaj przepis">Dodaj przepis</a>
                    <a href="/panel-uzytkownika/ksiazka-kucharska/" title="Ksiazka kucharska">Ksiażka kucharska</a>
                    <a href="/panel-uzytkownika/moje-dane/" title="Moje dane">Moje dane</a>
                    <a href="/zmien-haslo/" title="Zmień hasło">Zmień hasło</a>
                    <a href="/wylogowanie/" title="Wyloguj się">Wyloguj się</a>
    
                    <article id="top" style="margin-top:20px;">
                        <h2>Top 5 przepisów</h2>
                        <ul>
                    		{% if top_recipes %}
	                            {% for recipe in top_recipes %}
	                                <li><a href="/{{ recipe.2 }}">{{ recipe.0 }}</a></li>
	                            {% endfor %}
                            {% else %}
                            	<p>Baza jest pusta.</p>
                            {% endif %}
                        </ul>
                    </article>

                    <h2>Sponsorzy</h2>
                    {% for partner in partners %}
                    	<a href="{{ partner.href }}" title="{{ partner.name }}"><img src="{% url 'media' partner.logo %}" alt="{{ partner.name }}" title="{{ partner.name }}"></a>
                	{% endfor %}
                </section>
    
                <section id="content">
                    {% if userdataform %}
                        <h2>Moje dane</h2>
                        <form method="post" action="{{ request.path }}" style="float:left">
                            {% csrf_token %}
                            <fieldset>
                                <label for="id_fname">Imię:</label>
                                {{ userdataform.fname }}
                                {% if userdataform.fname.errors %}<p>{% for error in userdataform.fname.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_lname">Nazwisko:</label>
                                {{ userdataform.lname }}
                                {% if userdataform.lname.errors %}<p>{% for error in userdataform.lname.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_nick">Nick:</label>
                                {{ userdataform.nick }}
                                {% if userdataform.nick.errors %}<p>{% for error in userdataform.nick.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <button>Zapisz zmiany!</button>
                            </fieldset>
                        </form>
                        {% if changes == 0 %}
                            <p id="changes">Nie wprowadziłeś żadnych zmian.</p>
                        {% endif %}
                    {% elif addRecipe %}
                        <h2>Dodaj przepis</h2>
                        <form method="post" action="{{ request.path }}" enctype="multipart/form-data" style="float:left">
                            {% csrf_token %}
                            <fieldset>
                                <label for="id_name">Tytuł:</label>
                                {{ addRecipe.name }}
                                {% if addRecipe.name.errors %}<p>{% for error in addRecipe.name.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_category">Kategoria:</label>
                                {{ addRecipe.category }}
                                {% if addRecipe.category.errors %}<p>{% for error in addRecipe.category.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_text">Opis:</label>
                                {{ addRecipe.text }}
                                {% if addRecipe.text.errors %}<p>{% for error in addRecipe.text.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_products">Produkty:</label>
                                {{ addRecipe.products }}
                                {% if addRecipe.products.errors %}<p>{% for error in addRecipe.products.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <span style="float: left">{{ addRecipe.vegan }}Danie wegetariańskie</span>
                                {% if addRecipe.vegan.errors %}<p>{% for error in addRecipe.vegan.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <span style="float: left">{{ addRecipe.jude }}Danie koszerne</span>
                                {% if addRecipe.jude.errors %}<p>{% for error in addRecipe.jude.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <label for="id_photo" style="margin-top:50px;">Zdjęcie:</label>
                                {{ addRecipe.photo }}
                                {% if addRecipe.photo.errors %}<p>{% for error in addRecipe.photo.errors %}{{ error }}{% endfor %}</p>{% endif %}
                                <button>Dodaj przepis!</button>
                            </fieldset>
                        </form>
                    {% elif cookbook %}
                        <h2>Książka kucharska</h2>
                        {% if book.storage.all %}
                            <h3 style="width: 380px;margin-bottom:10px">W swojej książce masz już {{book.storage.count }} {% if book.storage.count == 0 or book.storage.count > 4 %}przepisów{% elif book.storage.count == 1 %}przepis{% else %}przepisy{% endif %}:</h3>
                            {% for recipe in book.storage.all %}
                                <p><a style="font-size: 15px; text-decoration: underline; display: inline;" href="/{{ recipe.url }}" title="{{ recipe }}">{{ recipe }}</a></p>
                            {% endfor %}
                        {% else %}
                            <p style="text-align: center;margin-top:65px;">Twoja książka kucharska na razie jest pusta.</p>
                            <p style="margin-top: 10px; text-align: center;">Wróć do <a style="font-size: 15px; text-decoration: underline; display: inline;" href="../../../../panel-uzytkownika/">panelu użytkownika</a>.</p>
                        {% endif %}
                    {% else %}
                        <p style="font-weight: bold">Witaj {% if user.nick %}{{ user.nick }}{% else %}{{ user.fname }}{% endif %},</p>
                        <p>Życzymy udanego gotowania z <a href="/" style="font-size:16px;font-size: 15px;text-decoration: underline;display: inline;">e-kk.pl</a>!</p>
                        <img src="{% url 'statics' 'images/cycki.png' %}" alt="" title="" width="500" height="333">
                        <p style="margin-top:10px;text-align: justify"><a href="/" style="font-size:16px;font-size: 15px;text-decoration: underline;display: inline;">e-kk.pl</a> to nowoczesna kuchnia i najlepsze przepisy kulinarne ze zdjęciami. Jeśli Twoja pasja to gotowanie oraz jedzenie to jest to miejsce dla Ciebie!</p>
                        <p style="margin-top:10px;text-align: justify">Znajdziesz u nas przepisy na wszelkie uroczystości rodzinne: urodziny, imieniny, święta, sylwestra i walentynki. A na deser znane i lubiane słodkości jak sernik waniliowy, babka marmurkowa, tiramisu, panna cotta, krem brule, trufla, tort czekoladowy i semifreddo i jeszcze więcej czekolady.</p>
                        <p style="margin-top:10px;text-align: justify; font-weight: bold">Smacznego!</p>
                    {% endif %}
                </section>
            </article>
        </section>
    {% endblock %}

core/templates/subpage.html
{% extends "index.html" %}
    {% load url from future %}

    <title>{% block title %}{% if error == "404" %}Nie znaleziono strony lub pliku{% elif error == "500" %}Wystąpił błąd serwera{% endif %}{{ subpage.title }}{% endblock %} - e-kk.pl</title>

    {% block content %}
        {% if subpage.flag == 1 %}
            <form method="post" action="{{ request.path }}">
                {% csrf_token %}
                <section id="register">
                    <h2 style="font-weight: bold; color: #FFF;text-shadow: -1px 0 #202e20,0 1px #202e20,1px 0 #202e20,0 -1px #202e20;">Rejestracja</h2>
                    <fieldset>
                        <label for="id_flname">Imię i nazwisko:</label>
                        {{ registerForm.flname }}
                        {% if registerForm.flname.errors %}<p>{% for error in registerForm.flname.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <label for="id_email">E-mail:</label>
                        {{ registerForm.email }}
                        {% if registerForm.email.errors %}<p>{% for error in registerForm.email.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <label for="id_nick">Nick:</label>
                        {{ registerForm.nick }}
                        {% if registerForm.nick.errors %}<p>{% for error in registerForm.nick.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <img src="/captcha.png/subpage_{{ subpage.id }}/" alt="Przepisz token z obrazka" title="Przepisz token z obrazka" width="120" height="30">
                        {{ registerForm.token }}
                        {% if registerForm.token.errors %}<p>{% for error in registerForm.token.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        {% if token_error %}<p>{{ token_error }}</p>{% endif %}
                        {{ registerForm.regulations }}<span>Oświadczam, że znam i akceptuję <a href="/regulamin/" title="regulamin">regulamin</a> serwisu.</span>
                        {% if registerForm.regulations.errors %}<p>{% for error in registerForm.regulations.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <button>Zarejestruj się!</button>
                    </fieldset>
                </section>
            </form>
        {% elif subpage.flag = 2 %}
            <form method="post" action="{{ request.path }}">
                {% csrf_token %}
                <section>
                    <h2 style="font-weight: bold; color: #FFF;text-shadow: -1px 0 #202e20,0 1px #202e20,1px 0 #202e20,0 -1px #202e20;">Logowanie</h2>
                    <fieldset>
                        <label for="id_login">Login:</label>
                        {{ loginForm.login }}
                        {% if loginForm.login.errors %}<p>{% for error in loginForm.login.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <label for="id_password">Hasło:</label>
                        {{ loginForm.password }}
                        {% if loginForm.password.errors %}<p>{% for error in loginForm.password.errors %}{{ error }}{% endfor %}</p>{% endif %}
                        <button>Zaloguj się!</button>
                    </fieldset>
                </section>
            </form>
        {% else %}
            <section>
                {% if error == "404" %}
                    <h2 style="font-weight: bold; color: #FFF;text-shadow: -1px 0 #202e20,0 1px #202e20,1px 0 #202e20,0 -1px #202e20;">Błąd 404</h2>
                    <p style="text-align:center;">Nie znaleziono strony lub pliku.</p>
                    <p style="margin-top: 10px; text-align: center;">Wróć do <a style="font-size: 15px; text-decoration: underline; display: inline;" href="/">strony głównej</a>.</p>
                {% elif error == "500" %}
                    <h2 style="font-weight: bold; color: #FFF;text-shadow: -1px 0 #202e20,0 1px #202e20,1px 0 #202e20,0 -1px #202e20;">Błąd 500</h2>
                    <p style="text-align:center;">Wystąpił błąd serwera</p>
                    <p style="margin-top: 10px; text-align: center;">Wróć do <a style="font-size: 15px; text-decoration: underline; display: inline;" href="/">strony głównej</a>.</p>
                {% else %}
                    <h2 style="font-weight: bold; color: #FFF;text-shadow: -1px 0 #202e20,0 1px #202e20,1px 0 #202e20,0 -1px #202e20;">{{ subpage.title }}</h2>
                    {{ subpage.text|safe }}
                {% endif %}
            </section>
        {% endif %}
    {% endblock %}